/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author layla
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
         setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jDesktopPaneMenu = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBarBarraDeMenu = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemCadastrarUser = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemCadastrarClien = new javax.swing.JMenuItem();
        jMenuVeiculo = new javax.swing.JMenu();
        jMenuItemCadastrarVeic = new javax.swing.JMenuItem();
        jMenuAluguel = new javax.swing.JMenu();
        jMenuItemCadastrarAlg = new javax.swing.JMenuItem();
        jMenuItemNaoDevolvidos = new javax.swing.JMenuItem();
        jMenuItemFaturamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(0, 0, 0));

        jDesktopPaneMenu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MENU.png"))); // NOI18N

        jDesktopPaneMenu.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneMenuLayout = new javax.swing.GroupLayout(jDesktopPaneMenu);
        jDesktopPaneMenu.setLayout(jDesktopPaneMenuLayout);
        jDesktopPaneMenuLayout.setHorizontalGroup(
            jDesktopPaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneMenuLayout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPaneMenuLayout.setVerticalGroup(
            jDesktopPaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneMenuLayout.createSequentialGroup()
                .addContainerGap(351, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBarBarraDeMenu.setBorder(null);
        jMenuBarBarraDeMenu.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenuUser.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuarioMenu.png"))); // NOI18N
        jMenuUser.setText("Funcionário");
        jMenuUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenuItemCadastrarUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCadastrarUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jMenuItemCadastrarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N
        jMenuItemCadastrarUser.setText("Funcionário");
        jMenuItemCadastrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTelaUsuario(evt);
            }
        });
        jMenuUser.add(jMenuItemCadastrarUser);

        jMenuBarBarraDeMenu.add(jMenuUser);

        jMenuCliente.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clienteMenu.png"))); // NOI18N
        jMenuCliente.setText("Clientes");
        jMenuCliente.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenuItemCadastrarClien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCadastrarClien.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jMenuItemCadastrarClien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cliente.png"))); // NOI18N
        jMenuItemCadastrarClien.setText("Cliente");
        jMenuItemCadastrarClien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTelaCliente(evt);
            }
        });
        jMenuCliente.add(jMenuItemCadastrarClien);

        jMenuBarBarraDeMenu.add(jMenuCliente);

        jMenuVeiculo.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/veiculoMenu.png"))); // NOI18N
        jMenuVeiculo.setText("Veículos");
        jMenuVeiculo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenuItemCadastrarVeic.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCadastrarVeic.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jMenuItemCadastrarVeic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/veiculo.png"))); // NOI18N
        jMenuItemCadastrarVeic.setText("Veículo");
        jMenuItemCadastrarVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTelaVeiculo(evt);
            }
        });
        jMenuVeiculo.add(jMenuItemCadastrarVeic);

        jMenuBarBarraDeMenu.add(jMenuVeiculo);

        jMenuAluguel.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuAluguel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aluguelMenu.png"))); // NOI18N
        jMenuAluguel.setText("Aluguel");
        jMenuAluguel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenuItemCadastrarAlg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCadastrarAlg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jMenuItemCadastrarAlg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aluguelIcon.png"))); // NOI18N
        jMenuItemCadastrarAlg.setText(" Aluguel");
        jMenuItemCadastrarAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTelaAluguel(evt);
            }
        });
        jMenuAluguel.add(jMenuItemCadastrarAlg);

        jMenuItemNaoDevolvidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemNaoDevolvidos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jMenuItemNaoDevolvidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/veiculoPendente.png"))); // NOI18N
        jMenuItemNaoDevolvidos.setText("Veiculos Pendentes");
        jMenuItemNaoDevolvidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTelaVeiculosPendentes(evt);
            }
        });
        jMenuAluguel.add(jMenuItemNaoDevolvidos);

        jMenuItemFaturamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemFaturamento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jMenuItemFaturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/faturamento.png"))); // NOI18N
        jMenuItemFaturamento.setText("Faturamento");
        jMenuItemFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTelaFaturamento(evt);
            }
        });
        jMenuAluguel.add(jMenuItemFaturamento);

        jMenuBarBarraDeMenu.add(jMenuAluguel);

        setJMenuBar(jMenuBarBarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(982, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subTelaUsuario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTelaUsuario

        TelaCadastroUsuario telacadUser = TelaCadastroUsuario.getInstancia();
        if (!telacadUser.isVisible()) {
            telacadUser.limpar();
            jDesktopPaneMenu.add(telacadUser);
            telacadUser.centralizar(jDesktopPaneMenu);
            telacadUser.setVisible(true);
            jDesktopPaneMenu.setComponentZOrder(telacadUser, 0);
        } else {
            telacadUser.requestFocus();
        }
        jDesktopPaneMenu.revalidate();
        jDesktopPaneMenu.repaint();
    
    }//GEN-LAST:event_subTelaUsuario

    private void subTelaCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTelaCliente

        TelaCadastroCliente telacadastclien = TelaCadastroCliente.getInstancia();
        if (!telacadastclien.isVisible()) {
            telacadastclien.limpar();
            jDesktopPaneMenu.add(telacadastclien);
            telacadastclien.centralizar(jDesktopPaneMenu);
            telacadastclien.setVisible(true);
            jDesktopPaneMenu.setComponentZOrder(telacadastclien, 0);
        } else {
            telacadastclien.requestFocus();
        }
        jDesktopPaneMenu.revalidate();
        jDesktopPaneMenu.repaint();
    }//GEN-LAST:event_subTelaCliente

    private void subTelaVeiculo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTelaVeiculo

        TelaCadastroVeiculo telacadastveic  = TelaCadastroVeiculo.getInstancia();
        if (!telacadastveic.isVisible()) {
            telacadastveic.limpar();
            jDesktopPaneMenu.add(telacadastveic );
            telacadastveic.centralizar(jDesktopPaneMenu);
            telacadastveic.setVisible(true);
            jDesktopPaneMenu.setComponentZOrder(telacadastveic , 0);
        } else {
            telacadastveic.requestFocus();
        }
        jDesktopPaneMenu.revalidate();
        jDesktopPaneMenu.repaint();
    }//GEN-LAST:event_subTelaVeiculo

    private void subTelaAluguel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTelaAluguel
         
        TelaCadastroAluguel telacadAlug   = TelaCadastroAluguel.getInstancia();
        if (!telacadAlug.isVisible()) {
            telacadAlug.limpar();
            jDesktopPaneMenu.add(telacadAlug  );
            telacadAlug.centralizar(jDesktopPaneMenu);
            telacadAlug.setVisible(true);
            jDesktopPaneMenu.setComponentZOrder(telacadAlug  , 0);
        } else {
            telacadAlug  .requestFocus();
        }
        jDesktopPaneMenu.revalidate();
        jDesktopPaneMenu.repaint();
    }//GEN-LAST:event_subTelaAluguel

    private void subTelaVeiculosPendentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTelaVeiculosPendentes

        TelaVeiculosPendentes telaveicpendentes = TelaVeiculosPendentes.getInstancia();
        if (!telaveicpendentes.isVisible()) {
            jDesktopPaneMenu.add(telaveicpendentes );
            telaveicpendentes.centralizar(jDesktopPaneMenu);
            telaveicpendentes.setVisible(true);
            jDesktopPaneMenu.setComponentZOrder(telaveicpendentes  , 0);
        } else {
            telaveicpendentes.requestFocus();
        }
        jDesktopPaneMenu.revalidate();
        jDesktopPaneMenu.repaint();
    }//GEN-LAST:event_subTelaVeiculosPendentes

    private void subTelaFaturamento(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTelaFaturamento

        TelaDeFaturamento telafaturamento = TelaDeFaturamento.getInstancia();
        if (!telafaturamento.isVisible()) {
            telafaturamento.limpar();
            jDesktopPaneMenu.add(telafaturamento );
            telafaturamento.centralizar(jDesktopPaneMenu);
            telafaturamento.setVisible(true);
            jDesktopPaneMenu.setComponentZOrder(telafaturamento  , 0);
        } else {
            telafaturamento.requestFocus();
        }
        jDesktopPaneMenu.revalidate();
        jDesktopPaneMenu.repaint();
    }//GEN-LAST:event_subTelaFaturamento

    /**
     * @param args the command line arguments
     */    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAluguel;
    private javax.swing.JMenuBar jMenuBarBarraDeMenu;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarAlg;
    private javax.swing.JMenuItem jMenuItemCadastrarClien;
    private javax.swing.JMenuItem jMenuItemCadastrarUser;
    private javax.swing.JMenuItem jMenuItemCadastrarVeic;
    private javax.swing.JMenuItem jMenuItemFaturamento;
    private javax.swing.JMenuItem jMenuItemNaoDevolvidos;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JMenu jMenuVeiculo;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables

 

}
