/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Entidades.Usuario;
import Repository.UsuarioRep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author layla
 */
public class TelaCadastroUsuario extends javax.swing.JInternalFrame {

    private static TelaCadastroUsuario instancia;

    
    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroUsuario() {
        initComponents();
        inicializarEstadoBotoes(); 
    }
    
     public static TelaCadastroUsuario getInstancia() {
        if (instancia == null) {
            instancia = new TelaCadastroUsuario();
        }
        return instancia;
    }
     
    private void inicializarEstadoBotoes() {
        btnCadastrarUser.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    } 
     
     
     public void centralizar(javax.swing.JDesktopPane parent) {
        int parentWidth = parent.getWidth();
        int parentHeight = parent.getHeight();
        int width = this.getWidth();
        int height = this.getHeight();

        int x = (parentWidth - width) / 2;
        int y = (parentHeight - height) / 2;

        this.setLocation(x, y);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadUser = new javax.swing.JPanel();
        jLTituloCadUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        texFieldNomeUser = new javax.swing.JTextField();
        TextFieldCargo = new javax.swing.JTextField();
        textFieldLoginUser = new javax.swing.JTextField();
        textFieldEmailUser = new javax.swing.JTextField();
        btnCadastrarUser = new javax.swing.JButton();
        jButtonSairUser = new javax.swing.JButton();
        jPasswordFieldSenhaUser = new javax.swing.JPasswordField();
        jLIdUser = new javax.swing.JLabel();
        tfIdUser = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        lbErro = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnLimpar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setForeground(new java.awt.Color(255, 255, 255));
        setTitle("Cadastro de  Funcionário");

        jLTituloCadUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLTituloCadUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloCadUser.setText("Cadastrar Funcionário");
        jLTituloCadUser.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cargo");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Senha");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        texFieldNomeUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TextFieldCargo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textFieldLoginUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textFieldEmailUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCadastrarUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnCadastrarUser.setText("Cadastrar");
        btnCadastrarUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar(evt);
            }
        });

        jButtonSairUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jButtonSairUser.setText("Sair");
        jButtonSairUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSairUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair(evt);
            }
        });

        jPasswordFieldSenhaUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLIdUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLIdUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIdUser.setText("ID");
        jLIdUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tfIdUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfIdUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnConsultar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alterar(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excluir(evt);
            }
        });

        lbErro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lbErro.setForeground(new java.awt.Color(153, 0, 0));
        lbErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbErro.setText("erro");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnLimpar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCampos(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadUserLayout = new javax.swing.GroupLayout(jPanelCadUser);
        jPanelCadUser.setLayout(jPanelCadUserLayout);
        jPanelCadUserLayout.setHorizontalGroup(
            jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadUserLayout.createSequentialGroup()
                .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLTituloCadUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadUserLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadUserLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfIdUser, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(texFieldNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(425, 425, 425)
                        .addComponent(jPasswordFieldSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(423, 423, 423)
                        .addComponent(textFieldEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(textFieldLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSairUser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadUserLayout.createSequentialGroup()
                                .addComponent(btnCadastrarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanelCadUserLayout.setVerticalGroup(
            jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadUserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbErro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLTituloCadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(texFieldNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPasswordFieldSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadUserLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(textFieldEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(textFieldLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanelCadUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtonSairUser)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCadUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 818, 552);
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar
    
    String nome = texFieldNomeUser.getText();
    String cargo = TextFieldCargo.getText();
    String login = textFieldLoginUser.getText();
    String senha = new String(jPasswordFieldSenhaUser.getPassword());
    String email = textFieldEmailUser.getText();

    UsuarioRep usuarioRep = new UsuarioRep();

    usuarioRep.cadastrarUser(nome, cargo, login, senha, email);
    limpar();

    }//GEN-LAST:event_Cadastrar

    private void Consultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar
         UsuarioRep usuarioRep = new UsuarioRep();

try {
    Usuario usuario = usuarioRep.consultarUsuario( tfIdUser.getText());

    if (usuario == null) {
        lbErro.setText("Funcionário não encontrado");
        return;
    }

    texFieldNomeUser.setText(usuario.getNome());
    TextFieldCargo.setText(usuario.getCargo());
    textFieldLoginUser.setText(usuario.getLogin());
    jPasswordFieldSenhaUser.setText(usuario.getSenha());
    textFieldEmailUser.setText(usuario.getEmail());

    btnExcluir.setEnabled(true);
    btnAlterar.setEnabled(true);

} catch (Exception ex) {
    Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "Ocorreu um erro ao consultar o funcionário: " + ex.getMessage());
}

    }//GEN-LAST:event_Consultar

    private void Alterar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alterar
        
      try {
    String idUsuarioStr = tfIdUser.getText(); 
    if (idUsuarioStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Informe o ID do funcionário.");
        return;
    }
    int idUsuario = Integer.parseInt(idUsuarioStr);

    String nome = texFieldNomeUser.getText();
    String cargo = TextFieldCargo.getText();
    String login = textFieldLoginUser.getText();
    String senha = jPasswordFieldSenhaUser.getText();
    String email = textFieldEmailUser.getText();  
    
    if (nome.isEmpty() || cargo.isEmpty() || login.isEmpty() || senha.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        return;
    }

    Usuario usuario = new Usuario();
    usuario.setIdUsuario(idUsuario); 
    usuario.setNome(nome);
    usuario.setCargo(cargo);
    usuario.setLogin(login);
    usuario.setSenha(senha);
    usuario.setEmail(email);
    
    UsuarioRep usuarioRep = new UsuarioRep();
    usuarioRep.alterar(usuario);

    JOptionPane.showMessageDialog(null, "Funcionário alterado com sucesso!");
    limpar();
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "ID do funcionário inválido.");
} catch (Exception ex) {
    Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "Erro ao alterar o funcionário: " + ex.getMessage());
}




    }//GEN-LAST:event_Alterar

    private void Excluir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excluir
        UsuarioRep usuarioRep = new UsuarioRep();

try {
    String idUsuario = tfIdUser.getText();

    if (idUsuario == null || idUsuario.trim().isEmpty()) {
        lbErro.setText("Digite um ID de funcionário válido.");
        return;
    }

    Usuario usuario = usuarioRep.consultarUsuario(idUsuario);

    if (usuario == null) {
        lbErro.setText("Funcionário não encontrado.");
        return;
    }

    int resposta = JOptionPane.showConfirmDialog(null, "Você deseja realmente excluir o funcionário?", "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);

    if (resposta == JOptionPane.YES_OPTION) {
        usuarioRep.excluirUsuario(usuario);

        Usuario usuarioVerificado = usuarioRep.consultarUsuario(idUsuario);

        if (usuarioVerificado == null) {
            JOptionPane.showMessageDialog(null, "Funcionário excluído com sucesso.");
            limpar();
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível excluir o funcionário.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "A exclusão foi cancelada.");
    }
} catch (Exception ex) {
    Logger.getLogger(TelaCadastroUsuario.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir o funcionário: " + ex.getMessage());
}

    }//GEN-LAST:event_Excluir

    private void Sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair
        this.dispose();
    }//GEN-LAST:event_Sair

    private void limparCampos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCampos
        texFieldNomeUser.setText("");
        TextFieldCargo.setText("");
        textFieldLoginUser.setText("");
        jPasswordFieldSenhaUser.setText("");
        textFieldEmailUser.setText("");
        tfIdUser.setText("");
        lbErro.setText("");
    }//GEN-LAST:event_limparCampos

   

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldCargo;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrarUser;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton jButtonSairUser;
    private javax.swing.JLabel jLIdUser;
    private javax.swing.JLabel jLTituloCadUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelCadUser;
    private javax.swing.JPasswordField jPasswordFieldSenhaUser;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbErro;
    private javax.swing.JTextField texFieldNomeUser;
    private javax.swing.JTextField textFieldEmailUser;
    private javax.swing.JTextField textFieldLoginUser;
    private javax.swing.JTextField tfIdUser;
    // End of variables declaration//GEN-END:variables

public void limpar(){
    texFieldNomeUser.setText("");
    TextFieldCargo.setText("");
    textFieldLoginUser.setText("");
    jPasswordFieldSenhaUser.setText("");
    textFieldEmailUser.setText("");
    tfIdUser.setText("");
    lbErro.setText("");
     
    inicializarEstadoBotoes();
}  
    
}
