/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Entidades.Aluguel;
import Entidades.ListarAluguelTableModel;
import Repository.AluguelRep;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author layla
 */
public class TelaListarAluguel extends javax.swing.JInternalFrame {
        
    private static TelaListarAluguel instancia;

   
    public static TelaListarAluguel getInstancia() {
        if (instancia == null) {
            instancia = new TelaListarAluguel();
        }
        return instancia;
    }

    private TelaListarAluguel() {
        super("Lista de Algueis", true, true, true, true);
        initComponents();
        mostrarListaAlugueis();
        pack();
    }
    
    
    public void centralizar(JDesktopPane parent) {
        int parentWidth = parent.getWidth();
        int parentHeight = parent.getHeight();
        int width = this.getWidth();
        int height = this.getHeight();

        int x = (parentWidth - width) / 2;
        int y = (parentHeight - height) / 2;

        this.setLocation(x, y);
    }
    
    
     private void mostrarListaAlugueis() {
         
    try {
        AluguelRep aluguelRep = new AluguelRep(); 
        List<Aluguel> alugueisList = aluguelRep.listarAlugueis(); 

        ListarAluguelTableModel rmf = new ListarAluguelTableModel(alugueisList);

        tabelaAlugueis.setModel(rmf);

        tabelaAlugueis.revalidate();
        tabelaAlugueis.repaint();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao obter alugueis: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
     
    public void atualizarTabelaAlugueis() {
    try {
        AluguelRep aluguelRep = new AluguelRep();
        List<Aluguel> alugueisList = aluguelRep.listarAlugueis();

        ListarAluguelTableModel rmf = new ListarAluguelTableModel(alugueisList);

        tabelaAlugueis.setModel(rmf);

        tabelaAlugueis.revalidate();
        tabelaAlugueis.repaint();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Erro ao atualizar tabela de alugueis: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}


    public static void main(String[] args) {
        JFrame frame = new JFrame("Teste");
        JDesktopPane desktopPane = new JDesktopPane();
        frame.setContentPane(desktopPane);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 600);

        TelaListarAluguel telaListarAluguel = TelaListarAluguel.getInstancia();
        desktopPane.add(telaListarAluguel);
        telaListarAluguel.setVisible(true);

        frame.setVisible(true);
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpListarAlg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlugueis = new javax.swing.JTable();

        setClosable(true);
        setTitle("Lista de Alugueis");

        tabelaAlugueis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaAlugueis);

        javax.swing.GroupLayout jpListarAlgLayout = new javax.swing.GroupLayout(jpListarAlg);
        jpListarAlg.setLayout(jpListarAlgLayout);
        jpListarAlgLayout.setHorizontalGroup(
            jpListarAlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListarAlgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpListarAlgLayout.setVerticalGroup(
            jpListarAlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListarAlgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpListarAlg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpListarAlg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpListarAlg;
    private javax.swing.JTable tabelaAlugueis;
    // End of variables declaration//GEN-END:variables

    
}

